# conda env create -f environment.yml
name: ecasdemo
channels:
  - birdhouse
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - ipywidgets
  - nodejs
  - birdhouse-birdy>=0.3.3
  - owslib>=0.17
  - python-cdo
  - pyophidia
  - cartopy
  - matplotlib
  - basemap
