# conda env create -f environment.yml
name: xrdemo
channels:
  - defaults
dependencies:
  - python=2.7
  - pip
  # jupyter
  - jupyterlab
  # xarray
  - xarray
  - dask
  - netcdf4
  - matplotlib
  # ESGF
  - esgf-pyclient
  - myproxyclient
