# conda env create -f environment.yml
name: xrdemo
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  # jupyter
  - jupyterlab
  # esgf
  - esgf-pyclient
  #- myproxyclient
  # xarray
  - xarray
  - dask
  - netcdf4
  - matplotlib
  - xesmf
  - zarr
  - cdo
  - python-cdo  
  #- pip:
  #  - myproxyclient
