# conda env create -f environment.yml
name: xrdemo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  # jupyter
  - jupyterlab
  # xarray
  - xarray
  - dask
  - netcdf4
  - matplotlib
  - xesmf
