name: demo
channels:
    - birdhouse
    - conda-forge
dependencies:
    - python=2.7
    - requests
    - jupyter
    - cartopy
    - esgf-pyclient
    - myproxyclient
    - netcdf4
    - nco
    - pynco
    - cdo=1.9.0=0
    - python-cdo=1.3.3
    - hdf5=1.8.18
    - ecmwf_grib=1.23.1=0
    - folium
