# conda env create -f environment.yml
name: pywps_profiles
channels:
  - birdhouse
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - ipywidgets
  - nodejs
  - birdhouse-birdy>=0.5
  - owslib>=0.17
  - pywps>=4.2
