# conda env create -f environment.yml
name: datedemo
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  # jupyter
  - jupyterlab
  # datelibs
  - iso8601
  - python-dateutil
  - arrow
  - pendulum
  - dateparser
